stages:
  - build
  - tests
  - webhook
  - deploy
build:
  stage: build
  image: node:12
  script:
    - cp .env.travis .env
    - sudo mysql -e 'create database testing;'
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
    - npm install
    - php artisan migrate
  cache:
    paths:
      - ./node_modules
      - ./vendor
  artifacts:
    expire_in: 1hour
    paths:
      - dist/my-app
  only:
    - main
    - develop
    - preprod
tests:
  stage: tests
  image: node:12
  script:
    - php artisan test
  only:
    - main
    - develop
    - preprod
webhook:
  stage: webhook
  image: node:12
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
  only:
    - main
    - develop
    - preprod
deploy:
  stage: deploy
  image: ruby:2.7
  script:
    - gem install dpl
    - dpl --provider=heroku --api-key=$HEROKU_KEY --master=$HEROKU_APP_PROD --pre-prod=$HEROKY_APP_PREPROD --dev=$HEROKU_APP_DEV
  only:
    - main
    - develop
    - preprod
