language: php
php:
- '7.4'
services:
- mysql
stages:
  - build
  - deploy
  - test
build:
  stage: build
  only:
    - main
    - develop
    - preprod
  before_script:
    - cp .env.travis .env
    - sudo mysql -e 'create database testing;'
    - composer self-update
  script:
    - composer install --prefer-source --no-interaction --dev
    - npm install
    - php artisan migrate
  cache:
    directories:
      - node_modules
      - vendor
deploy:
  provider: heroku
  api_key: "$HEROKU_KEY"
  app:
    master: "$HEROKU_APP_PROD"
    pre-prod: "$HEROKU_APP_PREPROD"
    dev: "$HEROKU_APP_DEV"
test:
  script:
    - php artisan test
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
redis:
  image: redis
  restart: always
  ports:
  - 16379:6379
