language: php
php:
  - '7.4'
  - '8.0'
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
script:
  - npm install
on:
  branch: main
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: $HEROKU_APP


redis:
  image: redis
  restart: always
  ports:
    - 16379:6379
